name: mobx_utils
description: This package provides utility functions and common MobX patterns build on top of MobX.
version: 0.3.0+1
homepage: https://github.com/amondnet/mobx_utils

environment:
  sdk: ^3.0.0


dependencies:
  mobx: ^2.0.0
#   path: ^1.8.0

dev_dependencies:
  lints: ^3.0.0
  test: ^1.16.0
  fake_async: